### ISSUE TITLE
DeviceNotFoundException from ServiceProxy

### ISSUE THREAD

**Issue by base-jumper** [fzankl/iot-hub-devicestreams-sample#2]
I get the following error from the `ServiceProxy` when trying to open an SSH connection. I am running the `DeviceProxy` and I have confirmed in the Azure portal that the device is reported as 'online' when the proxy is running.

```
info: ServiceProxy[0]
      Waiting for TCP clients...
info: ServiceProxy[0]
      Accepted TCP client using endpoint '127.0.0.1:2222'.
fail: ServiceProxy[0]
      An error occured during streaming session.
Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException: {"Message":"{\"errorCode\":404103,\"message\":\"The operation failed because the requested device isn't online or hasn't registered the direct method callback. To learn more, see https://aka.ms/iothub404103\",\"trackingId\":\"91317EB1EDB7441FAC14F1A5B951DB18-G2:-TimeStamp:2023-04-04T08:52:34.476950757+00:00\",\"timestampUtc\":\"2023-04-04T08:52:34.476950757+00:00\",\"info\":null}","ExceptionMessage":""}
   at Microsoft.Azure.Devices.HttpClientHelper.ExecuteAsync(HttpClient httpClient, HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isMappedToException, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.HttpClientHelper.ExecuteWithCustomOperationTimeoutAsync(HttpMethod httpMethod, Uri requestUri, TimeSpan operationTimeout, Func`3 modifyRequestMessageAsync, Func`2 isMappedToException, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.HttpClientHelper.PostAsync[T,T2](Uri requestUri, T entity, TimeSpan operationTimeout, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.AmqpServiceClient.CreateStreamAsync(Uri uri, DeviceStreamRequest deviceStreamRequest, CancellationToken cancellationToken)
   at IoTHubDeviceStreamSample.ServiceProxy.DeviceStream.HandleIncomingConnectionsAndCreateStreams(String deviceId, ServiceClient serviceClient, TcpClient tcpClient, CancellationTokenSource cancellationTokenSource) in C:\git\devicestreams-dev\src\ServiceProxy\DeviceStream.cs:line 57
```

I'm running .NET7.0.

**Comment by fzankl** [comment]
To narrow down the problem, I need some information.
Can you please state in which region you are using the Iot Hub itself?

**Comment by base-jumper** [comment]
The Iothub instance is running in south east Asia.

**Comment by tervoju** [comment]
getting now the same error. I was able to make it work earlier. device side seems to do this connect/disconnect cycle when waiting device stream connection. I assume the problem is in iothub.

![Image](https://github.com/user-attachments/assets/633f4452-4a71-4b6e-94a5-cc9584d4661d)

**Comment by tervoju** [comment]
changed the device protocol to Mqtt_websocket_only and it works.
